name: aws-lambda
on:
  push:
    branches:
      - prod-aws
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: npm install
      uses: Jaid/action-npm-install@v1.2.4
      with:
        # NODE_ENV setting for installing execution (affects the amount of dependencies installed, but I would recommend keeping development in any case).
        nodeEnv: UAT # optional, default is development
        # Can be "npm", "yarn", "pnpm" or "auto". "auto" will determine the package manager by looking into the repo's files. This is very accurate, so you normally don't want to change this.
        packageManager: npm # optional, default is auto
        # If true and node_modules folder already exists, this action will be skipped assuming npm install is not required.
        skipIfNodeModulesExists: false # optional, default is false
    
    - name: Serverless Package (Generate ZIP file)
      uses: SuprGames/serverless-github-action@v1.77
      with:
        # Serverless command including arguments
        command: package
        args: -v
        
#      THE FOLLOWING IS TO DEPLOY DIRECTLY
#    - name: Serverless GithubAction DEPLOY
#      uses: SuprGames/serverless-github-action@v1.77
#      with:
#        # Serverless command including arguments
#        command: deploy
#        args: -v
#      env:
#        # The AWS Credentials
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload the generated ZIP file to AWS Lambda function
      uses: mupixa/deploy-lambda@v0.4
      with:
        # Zip package of the complete Lambda source and dependencies.
        ZIP: .serverless/epw-serverless.zip
        # Name of the Lambda function
        FUNCTION_NAME: epw-serverless-dev-index
        # AWS secret key
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS secret key ID
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS region of the Lambda
        AWS_REGION: ap-southeast-2
